"""
Django settings for tawho_website project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%h$o9m9o34!)dcnn2o&0693&@amii^!#th730w6h_+2bxve4he'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'tawho_app',
     'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- Ongeza hapa
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


ROOT_URLCONF = 'tawho_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tawho_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',  # database name
        'USER': 'postgres.rxlbupzsfxjnoymmaqzl',  # database user
        'PASSWORD': 'NyumbaChap',  # database password
        'HOST': 'aws-1-us-east-1.pooler.supabase.com',  # database host
        'PORT': '5432',  # default PostgreSQL por
    }
}

# username: system
# pwd:TAWHO



# user=postgres.rxlbupzsfxjnoymmaqzl 
# password=[YOUR-PASSWORD] 
# host=aws-1-us-east-1.pooler.supabase.com
# port=5432
# dbname=postgres
# NyumbaChap

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True





JAZZMIN_SETTINGS = {
    "site_title": "TAWHO | Admin Dashboard",
    "site_header": "Tanzania Women Hope Organization",
    "site_brand": "TAWHO",
    "welcome_sign": "Welcome to the TAWHO Admin Dashboard",
    # "copyright": "© 2025 TAWHO",
    
    # Sidebar na navigation
    "show_sidebar": True,
    "navigation_expanded": True,
    "user_avatar": None,
    "search_model": None,  # Hakuna model ya generic

    # Top Menu Links (zimebadilishwa ziendane na kampuni)
    "topmenu_links": [
        {"name": "Home Page", "url": "/", "new_window": True},
        {"name": "About Us", "url": "/about/", "new_window": True},
        {"name": "Services", "url": "/services/", "new_window": True},
        {"name": "Contact", "url": "/contact/", "new_window": True},
    ],

    # Logo na branding
    "site_logo": None,  # Baadaye weka logo URL
    "site_logo_classes": "img-circle",
    "login_logo": None,
    "login_logo_dark": None,

    # Icons kwa app yako
    "icons": {
        "dpps_app.BlogPost": "fas fa-newspaper",
        "dpps_app.User_Testimonial": "fas fa-comment-dots",
        "dpps_app.ContactMessage": "fas fa-envelope",
        "dpps_app.Service": "fas fa-briefcase",
    },
}
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",           # theme ya default (light)
    # "theme": "flatly",           
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "show_ui_builder": False,
    "brand_colour": "navbar-primary",
    "dark_mode_theme": "darkly", # dark mode optional
}
